import './globals.css';
import { play } from './fonts';
import StarsCanvas from './components/StarBackground';

export const metadata = {
    title: 'NorixLab',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={play.className}>
                <StarsCanvas />

                {children}
            </body>
        </html>
    );
}
