
import React from 'react';

import Header from '../components/portfolio/header/Header';
import Footer from '../components/portfolio/footer/Footer';

export const metadata = {
    title: 'NorixLab | Portfolio',
    description: 'Generated by create next app',
};

const LayoutPortfolio = ({ children }) => {
    
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    );
};

export default LayoutPortfolio;
