import React from 'react';

import Header from '../components/portfolio/header/Header';


export const metadata = {
    title: 'NorixLab | Portfolio',
    description: 'Generated by create next app',
};

const LayoutPortfolio = ({ children }) => {
    return (
        <>
            <Header />
            {children}
            
        </>
    );
};

export default LayoutPortfolio;
